const actionTypes = Object.freeze({
  CREATE_ESTIMATED_EXPENSE: "CREATE_ESTIMATED_EXPENSE",
  CREATE_EXPENSE_CLAIM: "CREATE_EXPENSE_CLAIM",
  GET_LIST_EXPENSE_CLAIM: "GET_LIST_EXPENSE_CLAIM",
  GET_EXPENSE_CLAIM_BY_ID: "GET_EXPENSE_CLAIM_BY_ID"
});

export default actionTypes;
