const actionTypes = Object.freeze({
  CREATE_ESTIMATED_EXPENSE: "CREATE_ESTIMATED_EXPENSE",
  CREATE_EXPENSE_CLAIM: "CREATE_EXPENSE_CLAIM",
  GET_LIST_EXPENSE_CLAIM: "GET_LIST_EXPENSE_CLAIM"
});

export default actionTypes;
